xhr:
  status:
    error: 422
orderby:
  none: 0
  asce: 1
  desc: 2
  field:
    file: 'file'
    type: 'type'
    time: 'time'
    owner: 'owner'
event_type:
  copy: 0
  create: 1
  update: 2
  destroy: 3
  move: 4
  fromshare: 5
  fromshare_destroy: 6
  download: 7
